# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kayit_ol.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(452, 359)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.label_isim = QtWidgets.QLabel(Form)
        self.label_isim.setGeometry(QtCore.QRect(30, 80, 47, 13))
        self.label_isim.setObjectName("label_isim")
        self.label_soyisim = QtWidgets.QLabel(Form)
        self.label_soyisim.setGeometry(QtCore.QRect(30, 110, 47, 13))
        self.label_soyisim.setObjectName("label_soyisim")
        self.label_dogum_tarihi = QtWidgets.QLabel(Form)
        self.label_dogum_tarihi.setGeometry(QtCore.QRect(30, 140, 61, 20))
        self.label_dogum_tarihi.setObjectName("label_dogum_tarihi")
        self.label_dogum_yeri = QtWidgets.QLabel(Form)
        self.label_dogum_yeri.setGeometry(QtCore.QRect(30, 170, 71, 20))
        self.label_dogum_yeri.setObjectName("label_dogum_yeri")
        self.label_tc_no = QtWidgets.QLabel(Form)
        self.label_tc_no.setGeometry(QtCore.QRect(30, 210, 47, 13))
        self.label_tc_no.setObjectName("label_tc_no")
        self.label_tel_no = QtWidgets.QLabel(Form)
        self.label_tel_no.setGeometry(QtCore.QRect(30, 230, 47, 13))
        self.label_tel_no.setObjectName("label_tel_no")
        self.lineEdit_isim = QtWidgets.QLineEdit(Form)
        self.lineEdit_isim.setGeometry(QtCore.QRect(100, 80, 113, 20))
        self.lineEdit_isim.setObjectName("lineEdit_isim")
        self.lineEdit_soyisim = QtWidgets.QLineEdit(Form)
        self.lineEdit_soyisim.setGeometry(QtCore.QRect(100, 110, 113, 20))
        self.lineEdit_soyisim.setObjectName("lineEdit_soyisim")
        self.lineEdit_dogum_tarihi = QtWidgets.QLineEdit(Form)
        self.lineEdit_dogum_tarihi.setGeometry(QtCore.QRect(100, 140, 113, 20))
        self.lineEdit_dogum_tarihi.setObjectName("lineEdit_dogum_tarihi")
        self.lineEdit_dogum_yeri = QtWidgets.QLineEdit(Form)
        self.lineEdit_dogum_yeri.setGeometry(QtCore.QRect(100, 170, 113, 20))
        self.lineEdit_dogum_yeri.setObjectName("lineEdit_dogum_yeri")
        self.lineEdit_tc_no = QtWidgets.QLineEdit(Form)
        self.lineEdit_tc_no.setGeometry(QtCore.QRect(100, 200, 113, 20))
        self.lineEdit_tc_no.setObjectName("lineEdit_tc_no")
        self.lineEdit_tel_no = QtWidgets.QLineEdit(Form)
        self.lineEdit_tel_no.setGeometry(QtCore.QRect(100, 230, 113, 20))
        self.lineEdit_tel_no.setObjectName("lineEdit_tel_no")
        self.pushButton_Kayit_ol = QtWidgets.QPushButton(Form)
        self.pushButton_Kayit_ol.setGeometry(QtCore.QRect(300, 230, 75, 23))
        self.pushButton_Kayit_ol.setObjectName("pushButton_Kayit_ol")
        self.pushButton_Geri_git = QtWidgets.QPushButton(Form)
        self.pushButton_Geri_git.setGeometry(QtCore.QRect(300, 260, 75, 23))
        self.pushButton_Geri_git.setObjectName("pushButton_Geri_git")
        self.radioButton_erkek = QtWidgets.QRadioButton(Form)
        self.radioButton_erkek.setGeometry(QtCore.QRect(290, 140, 82, 17))
        self.radioButton_erkek.setObjectName("radioButton_erkek")
        self.radioButton_kadin = QtWidgets.QRadioButton(Form)
        self.radioButton_kadin.setGeometry(QtCore.QRect(290, 170, 82, 17))
        self.radioButton_kadin.setObjectName("radioButton_kadin")
        self.label_cinsiyet = QtWidgets.QLabel(Form)
        self.label_cinsiyet.setGeometry(QtCore.QRect(290, 120, 91, 16))
        self.label_cinsiyet.setObjectName("label_cinsiyet")
        self.label_baslik = QtWidgets.QLabel(Form)
        self.label_baslik.setGeometry(QtCore.QRect(120, 10, 231, 51))
        self.label_baslik.setMinimumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_baslik.setFont(font)
        self.label_baslik.setObjectName("label_baslik")
        self.label_kayit_sifre = QtWidgets.QLabel(Form)
        self.label_kayit_sifre.setGeometry(QtCore.QRect(30, 260, 47, 13))
        self.label_kayit_sifre.setObjectName("label_kayit_sifre")
        self.lineEdit_kayit_sifre = QtWidgets.QLineEdit(Form)
        self.lineEdit_kayit_sifre.setGeometry(QtCore.QRect(100, 260, 113, 20))
        self.lineEdit_kayit_sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_kayit_sifre.setObjectName("lineEdit_kayit_sifre")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_isim.setText(_translate("Form", "Isim"))
        self.label_soyisim.setText(_translate("Form", "Soyisim"))
        self.label_dogum_tarihi.setText(_translate("Form", "Dogum Tarihi"))
        self.label_dogum_yeri.setText(_translate("Form", "Dogum Yeri"))
        self.label_tc_no.setText(_translate("Form", "TC No"))
        self.label_tel_no.setText(_translate("Form", "Tel No"))
        self.pushButton_Kayit_ol.setText(_translate("Form", "Kayit Ol"))
        self.pushButton_Geri_git.setText(_translate("Form", "Geri Git"))
        self.radioButton_erkek.setText(_translate("Form", "Erkek"))
        self.radioButton_kadin.setText(_translate("Form", "Kadin"))
        self.label_cinsiyet.setText(_translate("Form", "Cinsiyet Sec"))
        self.label_baslik.setText(_translate("Form", "HOSGELDİN"))
        self.label_kayit_sifre.setText(_translate("Form", "Sifre"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
